name: first-workflow

on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print a message
        run: echo "hello from my first GitHub action"

      - name: Check Linting
        run: echo "Linting checking..."
      
  
